services:
  pre-utils:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: ceasear_kit
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/CeasearKit
    environment:
      - ENV=dev
      - DEBUG=true
    ports:
      - "8080:8080"
    working_dir: /home/CeasearKit/src/
    command: python /home/CeasearKit/src/main.py